# Generated by Django 4.0.4 on 2022-08-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_models', '0002_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
    ]
