# Generated by Django 4.1 on 2022-08-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_models', '0003_remove_booking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='car_i',
            new_name='car',
        ),
    ]
