# Generated by Django 4.0.4 on 2022-08-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_models', '0005_alter_image_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
